### ISSUE TITLE
rendering how to

### ISSUE THREAD

**Issue by glennmichaelmejias** [MasahideMori-SimpleAppli/simple_3d_renderer#2]
is it possible to render it with perspective and not orthographic?

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @glennmichaelmejias !

Try changing the Sp3dCamera arguments passed to the Sp3dRenderer.
For example, in the sample (https://pub.dev/packages/simple_3d_renderer/example),
Sp3dCamera(Sp3dV3D(0, 0, 3000), 6000)
Please change to:
Sp3dCamera(Sp3dV3D(0, 0, 400), 600)

When zoomed in from a distance like my example, it looks almost Orthographic.
