### ISSUE TITLE
physics

### ISSUE THREAD

**Issue by glennmichaelmejias** [MasahideMori-SimpleAppli/simple_3d_renderer#3]
is it possible to have physics simulation and add a group like make a car?

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @glennmichaelmejias ,

I think it's possible if you design your objects properly.
However, it is not suitable for full-scale rendering because it runs on the CPU (not the GPU, GPGPU). Rendering may take a long time if the parts are detailed or if there are a large number of parts.
(I'm not car expert so this answer may not be accurate.)

**Comment by glennmichaelmejias** [comment]
yeah. i tried 20,20,20 cube and it starts to slow down the fps. is there anything we can do about this?

**Comment by MasahideMori-SimpleAppli** [comment]
If the purpose is to move object in real time, it is difficult to move more than a certain number of objects (vertices) . CPU alone has its limits.
So, if you want to move in real time, you have to create a model with fewer vertices or use a language that can controll GPUs.
I don't know if there is a Flutter package that can handle GPUs.

If it's not realtime, you may be able to use a method such as converting the rendering result to an image.

**Comment by MasahideMori-SimpleAppli** [comment]
Speaking of which, if you don't mind if the physics calculation is not so accurate, you can also paste a PNG image to the low-polygon model. In this case, even real-time is fast.

The speedup techniques available will vary depending on what kind of project you are working on.

**Comment by glennmichaelmejias** [comment]
my target is only low poly games

**Comment by glennmichaelmejias** [comment]
is it possible to combine this two?
https://gitlab.com/jelenski/ditredi

**Comment by MasahideMori-SimpleAppli** [comment]
If games are your target, we recommend Unity. If it is a game engine, I think that high-speed rendering is possible using the GPU of a smartphone or the like.
Conversely, I do not recommend my package or ditredi.
My package is mainly for scientific computing.
I'm not familiar with ditredi, but I think it's probably unsuitable.

**Comment by glennmichaelmejias** [comment]
thanks. can you recommend language suitable for a 3d game engine for mobile?

**Comment by MasahideMori-SimpleAppli** [comment]
I'm not a game developer, but if you will use Unity, it's most likely C#.

**Comment by glennmichaelmejias** [comment]
no i mean. i want to create a mobile app that creates a 3d game. its a 3d game engine for mobile.

**Comment by MasahideMori-SimpleAppli** [comment]
Does that mean building something like Unity that works on mobile?
If so, you probably need to use Swift (iOS) and Kotlin (Android). You'll also need to learn how to properly render 3D on each platform. For example, Metal for iOS, OpenGL for Android, etc.
However, I think it's better to ask someone else than me. I'm not an expert in that field.

**Comment by glennmichaelmejias** [comment]
yes i already built, 2d version https://play.google.com/store/apps/details?id=com.mikeytronix.mobilegameengine. i want to build the 3d version but with using flutter.

**Comment by MasahideMori-SimpleAppli** [comment]
So cool! Have you tried this? I've only seen the demo, but it's probably more suitable than my package.
https://pub.dev/packages/three_dart

**Comment by MasahideMori-SimpleAppli** [comment]
I will close this question for now.
