### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by glennmichaelmejias** [MasahideMori-SimpleAppli/simple_3d_renderer#4]
does it detects object collisions with physics?

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @glennmichaelmejias ,

There are many ways to detect collisions. Calculate using Sp3dV3D (in simple_3d package) in the way that works best for your project.

For example, the simplest method is to calculate the center of all vertex coordinates and then approximate it with a sphere.
For a car, a square hitbox might be fine.

**Comment by glennmichaelmejias** [comment]
but how about the realtime collision? if im going to use square hitbox to a car, do it still be able to simulate drift, accelerations and braking?

**Comment by MasahideMori-SimpleAppli** [comment]
My package is for scientific computing, so it's all possible, but not for fast, rich, real-time rendering.
You should consider game engines instead of this package.
